### ISSUE TITLE
index.html: Broken link to github issues

### ISSUE THREAD

**Issue by chriz-uniba** [skohub-io/skohub.io#17]
https://github.com/skohub-io/skohub.io/blob/f8d5d63cd148d2974ae689e8d183b9a77b9e074f/index.html#L141

I guess it should be: https://github.com/skohub-io/skohub.io/issues
Removing the `skos:prefLab` in the `href`

**Comment by acka47** [comment]
Thanks for the pointer, @chriz-uniba! Will be fixed shortly.
