### ISSUE TITLE
Create new SkoHub logo

### ISSUE THREAD

**Issue by acka47** [skohub-io/skohub.io#20]
The process for the creation of a new SkoHub logo is already running. The steps are:

- [x] Answer and discuss questionnaire as provided by @kaimertens (https://github.com/skohub-io/skohub-vocabs/issues/189)
   -  The answers were provided by @acka47 with some additions by Andreas Wagner. 
   -  On 2022 @acka47, @kaimertens & @axenzen on 2022-06-21 met to discuss the questionnaire and added to the [pad with q&a](https://pad.gwdg.de/s/skohub-logo-entwicklung)
- [x] Create logo proposals (@kaimertens)
  - Kai has created the proposals (see [SkoHub-Logo.pdf](https://github.com/skohub-io/skohub.io/files/9211454/SkoHub-Logo.pdf))
- [x] Discuss proposals in the SkoHub community (i.e. in the [Rocket Chat](https://chat.gwdg.de/channel/skohub))

**Comment by acka47** [comment]
I posted the feedback today in the Rocket chat:

> Ich habe mir von verschiedenen Leuten eine Meinung eingeholt. Das Logo (das S) ist super und es gab daran keinerlei negative Kritik. Dazu ist es noch eine Evolution des alten Logos, besser geht es nicht. Danke dafür!
> Was den Oktopus angeht, finde ich den persönlich zu detailliert, wie aus einem Kinderbuch oder so. Ähnliche Rückmeldungen kamen auch von anderen ("comicartig", "verspielt" u.ä.). Es wäre super, wenn ihr da nochmal einen anderen Vorschlag machen könntet, der diese Rückmeldungen aufnimmt. Ok? Also vielleicht ein kleines bisschen weniger Details und zwar freundlich aber nicht übermäßig am Lächeln. (Das sind nur meine Ideen, wie das angegangen werden kann, @kaimertens  weiß das bestimmt besser.)

**Comment by axenzen** [comment]
Hallo @acka47, deine Rückmeldung hat uns etwas Kopfzerbrechen bereitet... Wenn der Krake weniger verspielt gestaltet wird, wird er andererseits auch schnell bedrohlich, und bei stärkerer Abstraktion zu nah an dem S-Teil des Logos. Das ist nicht so ganz leicht zu balancieren. Wir haben noch mal nachgebessert, aber grundsätzlich bleibt das Comicartige natürlich. Für uns wäre es völlig OK, wenn ihr euch gegen das Maskottchen und nur für das S-Logo entscheiden würdet.
[Krake_Gesichtsausdrücke.pdf](https://github.com/skohub-io/skohub.io/files/9401979/Krake_Gesichtsausdrucke.pdf)

**Comment by acka47** [comment]
As there is some legitimate doubt, I think, we should forego the mascot for now. We might revisit at a later time. I chave created two new tickets for implementing the changes (logo, colouring, fonts) on the  [SkoHub homepage](https://skohub.io) (#21) and on the SkoHub blog (https://github.com/skohub-io/skohub-blog/issues/14).

@kaimertens said he would create an overview/README on the logo etc. When this is ready, we can close this ticket.

**Comment by kaimertens** [comment]
Hallo @acka47 wichtig für die weitere Ausarbeitung sind Logo, Farben und Schriftdefinition. Sollten wir im weiteren Gestaltungsprozess feststellen, dass wir ein Maskottchen vermissen (oder andere Gestaltungselemente), können wir ja nachjustieren. Ich bereite die kleine Dokumentation auf und exportiere das Logo in unterschiedliche Formate. Im Laufe der kommenden Woche melde ich mich hierzu wieder. Danke und viele Grüße!

**Comment by acka47** [comment]
> Ich bereite die kleine Dokumentation auf und exportiere das Logo in unterschiedliche Formate. Im Laufe der kommenden Woche melde ich mich hierzu wieder. 

Gibt es hier mittlerweile was Neues, @kaimertens @axenzen?

**Comment by acka47** [comment]
Am 30. November werden @sroertgen und ich bei der SWIB einen SkoHub Workshop geben. Bekommen wir bis dahin das neue Logo und Design implementiert, @kaimertens & @axenzen ?

**Comment by kaimertens** [comment]
Hallo @acka47 ich sende dir per E-Mail die Ausarbeitung/Dokumentation zum Logo. Enthalten ist der Wandel vom alten zum neuen Logo (Logo-Evolution), die Format-Beschreibung, eine Positiv- und eine Negativ-Darstellung, Farben und Schriftart, sowie eine Anmerkung zu Formen, mit denen wir arbeiten können. Du kannst die Datei gerne öffentlich teilen und im Projekt teilen. Wenn du dazu Fragen hast, können wir uns spontan via Zoom kurzschließen.

Die Überarbeitung des Webdesigns starten wir jetzt. Der 30. November sollte machbar sein!

**Comment by acka47** [comment]
Danke, @kaimertens, die Datei liegt jetzt hier im Repo, siehe ae007c5b804db2bd4a48dfa68e3faabc602883bc.
