### ISSUE TITLE
Implement logo, font & colour changes in skohub.io

### ISSUE THREAD

**Issue by acka47** [skohub-io/skohub.io#21]
Depends on https://github.com/skohub-io/skohub.io/issues/20.

The resulting changes to the logo, fonts and colouring must be implemented in the static SkoHub homepage.

**Comment by acka47** [comment]
Deployed, see https://skohub.io/.

We've had some problems with relative links (must be something with the apache reverse proxy configuration) and added absolute links to skohub-io.github.io for now.)

Closing.

**Comment by acka47** [comment]
> I think the logo-link (index.html) is also affected by this... ?

Yes, it was. But now everything looks fine, right?

![image](https://user-images.githubusercontent.com/160292/204335257-ac81bf40-7a4e-449e-aa0c-63cc98290a33.png)

**Comment by kaimertens** [comment]
https://skohub.io/index.html ... linked in the header and footer (logo-click), throws a 404/Not Found.
