### ISSUE TITLE
Define and document SkoHub development guidelines

### ISSUE THREAD

**Issue by acka47** [skohub-io/skohub.io#24]
Add CONTRIBUTING.md with maintainer guidelines (see e.g. https://github.com/metafacture/metafacture-playground/blob/main/CONTRIBUTING.md)

**Comment by sroertgen** [comment]
Depends on https://github.com/skohub-io/skohub-vocabs/issues/242

**Comment by sroertgen** [comment]
Done with https://github.com/skohub-io/skohub-vocabs/issues/242
