### ISSUE TITLE
Host skohub.io on hbz servers

### ISSUE THREAD

**Issue by sroertgen** [skohub-io/skohub.io#28]
Also add monitoring.
Ping skohub.io and e.g. https://skohub.io/dini-ag-kim/ to test if skohub.io and SkoHub Vocabs are running

**Comment by dr0i** [comment]
Uh, there is already a error mail sent , we got one at `09.02.23, 17:25` with subject `monit alert -- Connection failed skohub.io`. It was sent to `lobid-admin`. We just ignored it somehow :/

**Comment by sroertgen** [comment]
We decided that we will continue to host the skohub.io site via github pages for now
