### ISSUE TITLE
Fix accessibility issues reported

### ISSUE THREAD

**Issue by sroertgen** [skohub-io/skohub.io#33]
Issues found by automated test on these pages:

- [https://skohub.io](https://skohub.io)

- [x] Prüfschritt 0.0.1 Erklärung zur Barrierefreiheit vorhanden
- [ ] Prüfschritt 0.0.3 Erläuterungen in Gebärdensprache vorhanden
- [ ] Prüfschritt 0.0.4 Erläuterungen in Leichter Sprache vorhanden
- [x] Prüfschritt 9.1.1.1 Nicht-Text-Inhalt
- [ ] Prüfschritt 12.2.3 Effektive Kommunikation

Extracted from 
[927_2023-09-05_12_32_BF_Pruefbericht_vereinfacht.pdf](https://github.com/skohub-io/skohub.io/files/14053476/927_2023-09-05_12_32_BF_Pruefbericht_vereinfacht.pdf)

**Comment by Phu2** [comment]
We need to provide a short alt text for this image

https://skohub-io.github.io/skohub.io/img/skohub-stage.svg

@sroertgen Can you come up with a suggestion?

**Comment by sroertgen** [comment]
"Illustration of the SkoHub modules SkoHub Vocabs, SkoHub Reconcile and SkoHub PubSub interacting with other open protocols and APIs like ActivityPub or the Reconciliation Service API."

**Comment by Phu2** [comment]
Re "Prüfschritt 12.2.3 Effektive Kommunikation" see https://ergebnis.bitvtest.de/pruefschritt/bitv-20-web/bitv-20-web-12-2-3-effektive-kommunikation

> ob eine Kontaktmöglichkeit zum Support über mindestens zwei verschiedene Kommunikations-Kanäle (z.B. Telefon und E-Mail) zur Verfügung steht

How about adding @acka47 's phone number (already published [here](https://www.hbz-nrw.de/ueber-uns/kontakt/ansprechpartner)) to https://lobid.org/team/ and link to this page?

**Comment by acka47** [comment]
> How about adding @acka47 's phone number (already published [here](https://www.hbz-nrw.de/ueber-uns/kontakt/ansprechpartner)) to https://lobid.org/team/ and link to this page?

The phone number is already there: https://lobid.org/team/ap/

**Comment by Phu2** [comment]
> The phone number is already there: https://lobid.org/team/ap/

jep, the phone number is included on most team members' page :+1: hopefully this is sufficient in terms of accessibility requirements.

Should we link to https://lobid.org/product/skohub/ or to https://lobid.org/team/ as the contact page for skohub.io?
