### ISSUE TITLE
bug: link of the logo on the homepage is broken

### ISSUE THREAD

**Issue by MyPyDavid** [skohub-io/skohub.io#35]
The link of the logo on https://skohub.io/ seems to be broken, I get a 404 on https://skohub.io/index.html.
I think that you could use more relative links in your `index.html` instead of absolute urls.  
Thanks for the presentation on SkoHub!

Ref:
https://github.com/skohub-io/skohub.io/blob/9f4116218a629b2c13d0f363f41f942ada830045/index.html#L17

**Comment by acka47** [comment]
Thanks for the pointer, @MyPyDavid ! We'll take care of it.

**Comment by sroertgen** [comment]
Thanks! Fixed with dadae8b93fea02b788a28ec83e045301795a130b
