### ISSUE TITLE
Improve structure and content of skohub.io

### ISSUE THREAD

**Issue by acka47** [skohub-io/skohub.io#36]
...as planned in the last MI organisation meeting. Might be related to #19 .

**Comment by acka47** [comment]
We collected some problems and ideas today in this pad: https://pad.lobid.org/skohub-webseite?both

Next step: Open a PR with "small fixes" and updated text for skohub.io

**Comment by sroertgen** [comment]
## Small fixes

- [X] make reconcile beta
- [X] Discourse link auf metadaten.community zeigen lassen
- [X] "Status: inactive" for editor, pubsub and extension (possibly under a separate heading collapsed with `<details>` tag)
- clearly show that reconciliation service is a demo application (probably also in URL)
- [X] add shape repo to web page
- Remove repos? 
    - https://github.com/skohub-io/skohub-validate
    - https://github.com/skohub-io/metadata-profiles
    - https://github.com/skohub-io/vocabs-monitoring
- [X] name for skohub-docker-vocabs repo could be improved. Ideas: skohub-vocabs-serverless, skohub-vocabs-pages

## Update text

What should the text focus on:

- SKOS publication made easy (short description of SKOS and where it is used)
- Features:
    - "serverless" setup
    - machine- and human-readable
    - git-based editorial workflows
- Example vocabularies
    - kerndatensatz forschung https://w3id.org/kdsf-ffk/
    - Hochschulfächersystematik: https://w3id.org/kim/hochschulfaechersystematik/scheme
- Get started in three steps: fork, edit, publish
- Additional options/features:
    - Run your own SkoHub
    - Set up Reconciliation Service API for your repo
- Reference implementations/users
    - wlo, oersi, tib, kim, iqb,...
